pr:
  branches:
    include:
      - develop
trigger:
  branches:
    include:
      - develop
jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: spice-storybook-variable-group
    steps:
      - checkout: self
        submodules: true
      - task: NodeTool@0
        inputs:
          versionSpec: '18.*'
        displayName: 'Node v18 needed.'

      - script: |
          yarn install --frozen-lockfile
          yarn build-storybook
        displayName: 'Yarn Build Storybook'

      # Create an archive of the output
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/storybook-static
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: $(build.artifactStagingDirectory)/drop/site.zip
          replaceExistingArchive: true
        displayName: 'Package build output'

      # Publish Build Artifact
      # Publish a local directory or file as a named artifact for the current pipeline.
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'Site'
          pathToPublish: $(build.artifactStagingDirectory)/drop/site.zip
        displayName: 'Publish deployment artifacts'

      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WAVE_053123210)
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/storybook-static' # App source code path
          api_location: '' # Api source code path - optional
          ###### End of Repository/Build Configurations ######
          skip_app_build: true
          skip_api_build: true
