#!/bin/bash

#COMMANDS
# ./toolkit git-commit
# ./toolkit generate-component

if [ "$1" = "git-commit" ]; then
  eval "sh .scripts/$1"

elif [ "$1" = "generate-component" ]; then
  eval "sh .scripts/$1"
fi
